### ISSUE TITLE
Facet does not wrap? 

### ISSUE THREAD

**Issue by jsekamane** [kristw/vega-desktop#11]
In VegaDesktop (v 3.1.0) when using `facet` the small multiple plots do not wrap, but are all on the same row.

Try the examples [Trellis Scatter Plot](https://vega.github.io/vega-lite/examples/trellis_scatter.html) or [Becker's Barley Trellis Plot](https://vega.github.io/vega-lite/examples/trellis_barley.html), and compare the layout in VegaDesktop vis-à-vis VegaEditor.

**Comment by domoritz** [comment]
Probably the version of Vega and Vega-Lite are outdated here. I haven’t updated them in a while. Will do soon.

**Comment by domoritz** [comment]
Fixed in 4.0
