### ISSUE TITLE
Debugging capabilities

### ISSUE THREAD

**Issue by nplatis** [kristw/vega-desktop#6]
It would be very useful if I could use vega-desktop to debug vega visualizations. Currently some error messages are printed, but without any context such as where they appear. Furthermore, printing the value of VEGA_DEBUG (see https://vega.github.io/vega/docs/api/debugging/) would provide much of the information needed. 

If access to the Chrome dev tools is possible, all this could be accomplished.

**Comment by kristw** [comment]
Added chrome dev tools in v1.5.0 
Please check it out. Thanks for suggesting.

**Comment by nplatis** [comment]
Thanks for working on it.
Unfortunately, I cannot seem to access the VEGA_DEBUG variable, and error messages still only appear on the graph; I cannot find them on the console with any additional info that Vega outputs.

What I was asking for was the info (VEGA_DEBUG, error messages) that appear on the Chrome dev tools console on the online Vega editor.

**Comment by kanitw** [comment]
Vega editor expose VEGA_DEBUG to the global scope too, so I guess that's the missing part here.

**Comment by kristw** [comment]
Oh, got it.. So I need to expose VEGA_DEBUG to the global scope in the error handler.

**Comment by kristw** [comment]
VEGA_DEBUG added in version 1.6.1
